name: Build and Deploy Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-
          # set latest tag for default branch
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and test Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          SSH_PASSWORD=${{ secrets.SSH_PASSWORD || 'defaultpassword' }}

    - name: Test Docker image
      run: |
        # Build the image for testing
        docker build -t kali-ai-agent:test \
          --build-arg SSH_PASSWORD=${{ secrets.SSH_PASSWORD || 'defaultpassword' }} .

        # Run basic tests
        docker run --rm --name test-container kali-ai-agent:test /bin/bash -c "
          echo 'Testing SSH service...'
          service ssh start
          sleep 2
          service ssh status | grep -q 'active' && echo '✓ SSH service is running' || exit 1

          echo 'Testing Python installation...'
          python3 --version

          echo 'Testing pip installation...'
          pip3 --version

          echo 'Testing git installation...'
          git --version

          echo 'Testing if term_agent directory exists...'
          [ -d '/term_agent' ] && echo '✓ term_agent directory exists' || exit 1

          echo 'All tests passed!'
        "

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: kali-ai-agent:test
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-
          # set latest tag for default branch
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          SSH_PASSWORD=${{ secrets.SSH_PASSWORD || 'defaultpassword' }}

    - name: Generate artifact attestation
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "Generating SBOM attestation for tagged release"
        # This would generate a Software Bill of Materials (SBOM) attestation
        # You can customize this based on your needs

    - name: Notify deployment
      run: |
        echo "Docker image deployed successfully!"
        echo "Image: ${{ steps.meta.outputs.tags }}"
        echo "Digest: ${{ steps.build.outputs.digest }}"
